@ignore
Feature: Test Data for Groups

  Scenario: Input table for Creating Customer and users
    * table userdata
      | testcase  | userName      | name           | verified | disabled | groupName        | groupLevelSharing | email                          | policies                                                                                                                                                              |
      | "OBS-159" | "systemadmin" | "APIAdminUser" | true     | false    | "ADMIN"          | "false"           | "systemAdmin@sample.com"   | [{"id":1,"name":"AllowALL","description":"Admin Policy","resourceId":"*","resourceType":"*","rule":"true","effect":"ALLOW","display":true,"groupLevelSharing":false}] |
      | "OBS-160" | "obsadmin"    | "APIObsAdmin"  | true     | false    | "OBSERVE_ADMIN"  | "false"           | "observeAdmin@sample.com"  |                                                                                                                                                                       |
      | "OBS-161" | "obsviewer"   | "APIObsView"   | true     | false    | "OBSERVE_VIEWER" | "false"           | "observeViewer@sample.com" |                                                                                                                                                                       |

    * table customerdata
      | testcase          | userName     | name           | verified | disabled | groupName         | email                    | industryType      | customerName | region          | monitoringToolType | Critical | High | Medium | expectedStatus | expectedMessage                                                       | Scenario                                                                                |
      | "OBS-159,OBS-226" | "sysadmin"   | "APIadmintest" | true     | false    | "ADMIN"           | "admintest@sample.com"   | "Aerospace"       | "customer01" | "EMEA"          | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"                                                            | "Admin create customer with all valid details"                                          |
      | "OBS-77"          | "obsadmin"   | "APIaobsadmin" | true     | false    | "OBSERVE_ADMIN"   | "adminobs@sample.com"    | "Computer"        | "customer02" | "EMEA"          | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"                                                            | "Observe admin create customer with all valid details"                                  |
      | "OBS-161"         | "obsviewer"  | "APIobsview"   | true     | false    | "OBSERVE_VIEWER"  | "adminview@sample.com"   | "Computer"        | "customer03" | "APAC"          | "Azure"            | 20       | 60   | 80     | 400            | "User is not Authorized to Perform Save on Customer"                  | "Observe viewer user try to create customer"                                            |
      | "OBS-95"          | "nonobsuser" | "APInonobs"    | true     | false    | "CLOUD_ARCHITECT" | "adminnonobs@sample.com" | "Computer"        | "customer04" | "APAC"          | "Azure"            | 20       | 60   | 80     | 403            | "User is not allowed to perform Create operation on ObserveCustomer." | "Observe viewer CLOUD_ARCHITECT user try to create customer"                            |
      | "OBS-174"         | "obsadmin"   | "APIobsadmin"  | true     | false    | "OBSERVE_ADMIN"   | "adminobs@sample.com"    | "Computer"        | "customer05" | "invalidRegion" | "Azure"            | 20       | 60   | 80     | 400            | "##ignore"                                                            | "Observe admin create customer with invalid region"                                     |
      | "OBS-174"         | "obsadmin"   | "APIobsadmin"  | true     | false    | "OBSERVE_ADMIN"   | "adminobs@sample.com"    | "invalidIndustry" | "customer06" | "APAC"          | "Azure"            | 20       | 60   | 80     | 400            | "##ignore"                                                            | "Observe admin create customer with invalid Industry"                                   |
      | "OBS-174"         | "obsadmin"   | "APIobsadmin"  | true     | false    | "OBSERVE_ADMIN"   | "adminobs@sample.com"    | "Computer"        | " "          | "APAC"          | "Azure"            | 20       | 60   | 80     | 400            | "Customer name cannot be blank"                                       | "Verify api allows to create customer with blank name"                                  |
      | "OBS-174"         | "obsadmin"   | "APIadmintest" | true     | false    | "OBSERVE_ADMIN"   | "admintest@sample.com"   | "Aerospace"       | "c"          | "EMEA"          | "Azure"            | 20       | 60   | 80     | 400            | "Customer name input length must be greater than 3 characters"        | "Verify error when admin create customer with 1 character"                              |
      | "OBS-174"         | "obsadmin"   | "APIadmintest" | true     | false    | "OBSERVE_ADMIN"   | "admintest@sample.com"   | "Aerospace"       | "%%%%"       | "EMEA"          | "Azure"            | 20       | 60   | 80     | 400            | "Customer name must be alphanumeric"                                  | "Verify error when admin create customer with special characters"                       |
      | "OBS-174"         | "obsadmin"   | "APIadmintest" | true     | false    | "OBSERVE_ADMIN"   | "admintest@sample.com"   | "Aerospace"       | "test"       | "EMEA"          | "Azure"            | 20       | 101  | 80     | 400            | "High value must be in the range 1-100"                               | "Verify error when admin create customer with High value above 100"                     |
      | "OBS-174"         | "obsadmin"   | "APIadmintest" | true     | false    | "OBSERVE_ADMIN"   | "admintest@sample.com"   | "Aerospace"       | "test"       | "EMEA"          | "Azure"            | 20       | 60   | 101    | 400            | "Medium value must be in the range 1-100"                             | "Verify error when admin create customer with medium value above 100"                   |
      | "OBS-174"         | "obsadmin"   | "APIadmintest" | true     | false    | "OBSERVE_ADMIN"   | "admintest@sample.com"   | "Aerospace"       | "test"       | "EMEA"          | "Azure"            | 101      | 99   | 80     | 400            | "Critical value must be in the range 1-100"                           | "Verify error when admin create customer with critical value above 100"                 |
      | "OBS-174"         | "obsadmin"   | "APIadmintest" | true     | false    | "OBSERVE_ADMIN"   | "admintest@sample.com"   | "Aerospace"       | "test"       | "EMEA"          | "Azure"            | 90       | 10   | 99     | 400            | "Critical value cannot be greater than/equal to High/Medium value"    | "Verify error when admin create customer with Critical value greater than High"         |
      | "OBS-174"         | "obsadmin"   | "APIadmintest" | true     | false    | "OBSERVE_ADMIN"   | "admintest@sample.com"   | "Aerospace"       | "test"       | "EMEA"          | "Azure"            | 30       | 40   | 20     | 400            | "Medium value cannot be less than/equal to Critical/High value"       | "Verify error when admin create customer with Medium value less than to Critical value" |
      | "OBS-174"         | "obsadmin"   | "APIadmintest" | true     | false    | "OBSERVE_ADMIN"   | "admintest@sample.com"   | "Aerospace"       | "test"       | "EMEA"          | "Azure"            | 4        | 5    | 5      | 400            | "Medium value cannot be less than/equal to Critical/High value"       | "Verify error when admin create customer with Medium value less than to High value"     |
      | "OBS-174"         | "obsadmin"   | "APIadmintest" | true     | false    | "OBSERVE_ADMIN"   | "admintest@sample.com"   | "Aerospace"       | "test"       | "EMEA"          | "Azure"            | 5        | 5    | 10     | 400            | "Critical value cannot be greater than/equal to High/Medium value"    | "Verify error when admin create customer with Critical value greater than Medium"       |

    * table getcustomerdata
      | testcase          | userName   | name           | verified | disabled | groupName | email                  | industryType | customerName  | region | monitoringToolType | Critical | High | Medium | expectedStatus | expectedMessage | Scenario                                         |
      | "OBS-340,OBS-174" | "obsadmin" | "APIadmintest" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "getcustomer" | "EMEA" | "Azure"            | 30       | 70   | 85     | 200            | "##ignore"      | "Verify Get Customer API with required details " |

    * table deletecustomer
      | testcase | userName   | name          | verified | disabled | groupName       | email                 | industryType | customerName | region | monitoringToolType | Critical | High | Medium | expectedStatus | expectedMessage | Scenario                                                                   |
      | "OBS-88" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "adminobs@sample.com" | "Computer"   | "customer07" | "APAC" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Verify deleted customers are not listed when user hits list customer api" |
      | "OBS-89" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "adminobs@sample.com" | "Computer"   | "customer08" | "APAC" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Verify api error when user delete customer which does not exists"         |

    * table createcustomerwithonlyname
      | testcase  | userName   | name          | verified | disabled | groupName       | email                 | industryType | customerName | region     | monitoringToolType | Critical | High | Medium | expectedStatus | expectedMessage | Scenario                                                                |
      | "OBS-171" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "adminobs@sample.com" | "##ignore"   | "customer09" | "##ignore" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Verify api allows to create customer without Industry type and Region" |

    * table updatecustomerdata
      | testcase  | userName   | name          | verified | disabled | groupName | email                  | industryType | customerName | region | monitoringToolType | Critical | High | Medium | expectedStatus | expectedMessage | updatedIndustryType | updatedName    | updatedRegion   | updatedCritical | updatedHigh | updatedMedium | expectedUpdateStatus | expectedUpdateMessage                                              | Scenario                                                                          |
      | "OBS-78"  | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer10" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Computer"          | "updatedName"  | "AMER"          | 30              | 50          | 70            | 200                  | "##ignore"                                                         | "Admin user update customer name Industry Region"                                 |
      | "OBS-175" | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer11" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Computer"          | "customer1198" | "InvalidRegion" | 30              | 50          | 70            | 400                  | "##ignore"                                                         | "Admin user update customer with invalid Region"                                  |
      | "OBS-175" | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer12" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Computer"          | " "            | "AMER"          | 30              | 50          | 70            | 400                  | "Customer name cannot be blank"                                    | "Admin user update customer name as blank"                                        |
      | "OBS-175" | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer13" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Computer"          | "c"            | "AMER"          | 30              | 50          | 70            | 400                  | "Customer name input length must be greater than 3 characters"     | "Admin user update customer with less than 3 characters"                          |
      | "OBS-175" | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer14" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Computer"          | "%#%#%#%"      | "AMER"          | 30              | 50          | 70            | 400                  | "Customer name must be alphanumeric"                               | "Admin user update customer with all special characters"                          |
      | "OBS-175" | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer15" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "InvalidIndustry"   | "customer11"   | "AMER"          | 30              | 50          | 70            | 400                  | "##ignore"                                                         | "Admin user update customer with invalid Industry Type"                           |
      | "OBS-175" | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer10" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Computer"          | "updatedName"  | "AMER"          | 20              | 101         | 80            | 400                  | "High value must be in the range 1-100"                            | "Verify error when admin edit customer with High value above 100"                 |
      | "OBS-175" | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer10" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Computer"          | "updatedName"  | "AMER"          | 20              | 60          | 101           | 400                  | "Medium value must be in the range 1-100"                          | "Verify error when admin edit customer with medium value above 100"               |
      | "OBS-175" | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer10" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Computer"          | "updatedName"  | "AMER"          | 101             | 99          | 80            | 400                  | "Critical value must be in the range 1-100"                        | "Verify error when admin edit customer with critical value above 100"             |
      | "OBS-175" | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer10" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Computer"          | "updatedName"  | "AMER"          | 90              | 10          | 99            | 400                  | "Critical value cannot be greater than/equal to High/Medium value" | "Verify error when admin edit customer with Critical value greater than High"     |
      | "OBS-175" | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer10" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Computer"          | "updatedName"  | "AMER"          | 5               | 95          | 10            | 400                  | "Medium value cannot be less than/equal to Critical/High value"    | "Verify error when admin edit customer with Medium value less than to High value" |
      | "OBS-175" | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer10" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Computer"          | "updatedName"  | "AMER"          | 4               | 5           | 5             | 400                  | "Medium value cannot be less than/equal to Critical/High value"    | "Verify error when admin edit customer with Medium value less than to High value" |
      | "OBS-175" | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer10" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Computer"          | "updatedName"  | "AMER"          | 5               | 5           | 10            | 400                  | "Critical value cannot be greater than/equal to High/Medium value" | "Verify error when admin edit customer with Critical value greater than Medium"   |

    * table validateupdatecustomerdata
      | testcase  | userName | name          | verified | disabled | groupName       | email                  | industryType | customerName | region | monitoringToolType | Critical | High | Medium | expectedStatus | expectedMessage | UpdatedUserName | updatedIndustryType | updatedName    | updatedRegion | updatedCritical | updatedHigh | updatedMedium | expectedUpdateStatus | expectedUpdateMessage | Scenario                                  |
      | "OBS-176" | "admin"  | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Computer"   | "customer16" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "obsadmin"      | "Aerospace"         | "customer1578" | "AMER"        | 30              | 50          | 70            | 200                  | "##ignore"            | "Validate edit and  update customer data" |

    * table customerdatawithoutmonitoringtool
      | testcase  | userName   | name           | verified | disabled | groupName | email                  | industryType | customerName | region | Critical | High | Medium | expectedStatus | expectedMessage                                  | Scenario                                          |
      | "OBS-228" | "obsadmin" | "APIadmintest" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer87" | "EMEA" | 20       | 60   | 80     | 400            | "Cannot save customer without monitoring system" | "Admin create customer without monitoring system" |

    * table updatecustomerdatawithoutmonitoringtool
      | testcase  | userName   | name          | verified | disabled | groupName | email                  | industryType | customerName | region | monitoringToolType | Critical | High | Medium | expectedStatus | expectedMessage | updatedIndustryType | updatedName   | updatedRegion | updatedCritical | updatedHigh | updatedMedium | expectedUpdateStatus | expectedUpdateMessage                            | Scenario                                          |
      | "OBS-229" | "obsadmin" | "APIobsadmin" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer18" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Computer"          | "updatedName" | "AMER"        | 30              | 50          | 70            | 400                  | "Cannot save customer without monitoring system" | "Admin user update customer name Industry Region" |

    * table customerdataformultiplemonitoringtool
      | testcase  | userName   | name           | verified | disabled | groupName | email                  | industryType | customerName | region | monitoringToolType | Critical | High | Medium | expectedStatus | expectedMessage | Scenario                                       |
      | "OBS-227" | "obsadmin" | "APIadmintest" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer19" | "EMEA" | "Azure"            | 20       | 60   | 80     | 200            | "##ignore"      | "Admin create customer with all valid details" |

    * table createslodata
      | testcase  | userName   | name          | verified | disabled | groupName       | email                  | industryType | customerName   | region | monitoringToolType | name                                  | SLOType        | target | windowType | timeWindow | Critical | High | Medium | calendarPeriod | Duration | Timeunit       | expectedStatus | expectedMessage | Scenario                                                              |
      | "OBS-222" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "SLO_Availability_Calendar_DAY"       | "Availability" | 99     | "Calendar" | null       | 20       | 40   | 50     | "DAY"          | 100      | "milliseconds" | 200            | "##ignore"      | "Verify SLO creation with Availability and Calendar DAY window"       |
      | "OBS-222" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer2" | "APAC" | "Azure"            | "SLO_Availability_Calendar_WEEK"      | "Availability" | 99     | "Calendar" | null       | 30       | 60   | 70     | "WEEK"         | 100      | "milliseconds" | 200            | "##ignore"      | "Verify SLO creation with Availability and Calendar WEEK window"      |
      | "OBS-222" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer3" | "APAC" | "Azure"            | "SLO_Availability_Calendar_MONTH"     | "Availability" | 99     | "Calendar" | null       | 40       | 50   | 80     | "MONTH"        | 100      | "milliseconds" | 200            | "##ignore"      | "Verify SLO creation with Availability and Calendar MONTH window"     |
      | "OBS-222" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer4" | "APAC" | "Azure"            | "SLO_Availability_Calendar_QUARTER"   | "Availability" | 99     | "Calendar" | null       | 60       | 70   | 90     | "QUARTER"      | 100      | "milliseconds" | 200            | "##ignore"      | "Verify SLO creation with Availability and Calendar QUARTER window"   |
      | "OBS-222" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer5" | "APAC" | "Azure"            | "SLO_Availability_Calendar_FORTNIGHT" | "Availability" | 99     | "Calendar" | null       | 20       | 50   | 60     | "FORTNIGHT"    | 100      | "milliseconds" | 200            | "##ignore"      | "Verify SLO creation with Availability and Calendar FORTNIGHT window" |
      | "OBS-222" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer6" | "APAC" | "Azure"            | "SLO_Availability_Rolling"            | "Availability" | 99     | "Rolling"  | 40         | 30       | 70   | 85     | "##ignore"     | 100      | "milliseconds" | 200            | "##ignore"      | "Verify SLO creation with Availability and Rolling window"            |
      | "OBS-222" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer7" | "APAC" | "Azure"            | "SLO_Latency_Calendar"                | "Latency"      | 90     | "Calendar" | null       | 40       | 80   | 90     | "WEEK"         | 100      | "milliseconds" | 200            | "##ignore"      | "Verify SLO creation with Latency and Calendar window"                |
      | "OBS-222" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer8" | "APAC" | "Azure"            | "SLO_Latency_Rolling"                 | "Latency"      | 50     | "Rolling"  | 10         | 50       | 90   | 99     | "##ignore"     | 2        | "seconds"      | 200            | "##ignore"      | "Verify SLO creation with Latency and Rolling window"                 |

    * table getslodata
      | testcase                  | userName   | name          | verified | disabled | groupName       | email                  | industryType | customerName    | region | monitoringToolType | SLOApplicationService          | SLOName                     | SLOType        | SLOTarget | SLOWindowType | SLOTimeWindow | CriticalThreshold | HighThreshold | MediumThreshold | calendarPeriod | expectedStatus | expectedMessage | Scenario                    |
      | "OBS-425,OBS-426,OBS-427" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "GetSLODetails" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO_Availability_Calendar" | "Availability" | 99        | "Calendar"    | 30            | 20                | 50            | 60              | "WEEK"         | 200            | "##ignore"      | "Verify Get SLO Detail API" |

    * table slodatawithoutmandotoryfield
      | testcase  | userName   | name          | verified | disabled | groupName       | email                  | industryType | customerName   | region | monitoringToolType | SLOApplicationService          | SLOName     | SLOType        | SLOTarget   | SLOWindowType | SLOTimeWindow | CriticalThreshold | HighThreshold | MediumThreshold | calendarPeriod | expectedStatus | expectedMessage | expectedSLOResponseStatus | expectedSLOResponseMessage                                                | Scenario                                                                              |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "RemoveKey" | "Availability" | 99          | "Calendar"    | 20            | 20                | 50            | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | 'SLO name cannot be blank'                                                | "Verify SLO without SLO Name"                                                         |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "RemoveKey"                    | "SLO1"      | "Availability" | 99          | "Calendar"    | 20            | 20                | 50            | 60              | "DAY"          | 200            | "##ignore"      | 400                       | 'SLO Application service cannot be blank'                                 | "Verify SLO creation without application service"                                     |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO2"      | "RemoveKey"    | 99          | "Calendar"    | 20            | 20                | 50            | 60              | "MONTH"        | 200            | "##ignore"      | 400                       | 'SLO Type should be specified'                                            | "Verify SLO creation without SLO Type"                                                |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO3"      | "Availability" | "RemoveKey" | "Calendar"    | 20            | 20                | 50            | 60              | "DAY"          | 200            | "##ignore"      | 400                       | 'SLO target value cannot be empty'                                        | "Verify SLO creation without SLO Target"                                              |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO4"      | "Availability" | 99          | "RemoveKey"   | 20            | 20                | 50            | 60              | "DAY"          | 200            | "##ignore"      | 400                       | 'SLO Window Type should be specified'                                     | "Verify SLO creation without SLO Window Type"                                         |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO5"      | "Availability" | 99          | "Calendar"    | 20            | 'RemoveKey'       | 50            | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | 'Error budget critical status threshold for the SLO cannot be empty'      | "Verify SLO creation without Critical Threshold"                                      |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO6"      | "Availability" | 99          | "Calendar"    | 20            | 20                | 'RemoveKey'   | 60              | "MONTH"        | 200            | "##ignore"      | 400                       | 'Error budget high status threshold for the SLO cannot be empty'          | "Verify SLO creation without high Threshold"                                          |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO7"      | "Availability" | 99          | "Calendar"    | 20            | 20                | 50            | 'RemoveKey'     | "QUARTER"      | 200            | "##ignore"      | 400                       | 'Error budget medium status threshold for the SLO cannot be empty'        | "Verify SLO creation without Medium Threshold"                                        |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO8"      | "Availability" | 99          | "Rolling"     | 'RemoveKey'   | 20                | 50            | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | 'Time Window cannot be null for SLO with Rolling window'                  | "Verify SLO creation without Time Window"                                             |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | " "         | "Availability" | 99          | "Calendar"    | 20            | 20                | 50            | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | 'SLO name cannot be blank'                                                | "Verify SLO with blank SLO Name"                                                      |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | " "                            | "SLO1"      | "Availability" | 99          | "Rolling"     | 20            | 20                | 50            | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | 'SLO Application service cannot be blank'                                 | "Verify SLO creation with blank application service"                                  |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO2"      | " "            | 99          | "Calendar"    | 20            | 20                | 50            | 60              | "DAY"          | 200            | "##ignore"      | 400                       | "##ignore"                                                                | "Verify SLO creation with blank SLO Type"                                             |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO3"      | "Availability" | " "         | "Calendar"    | 20            | 20                | 50            | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | "##ignore"                                                                | "Verify SLO creation with blank SLO Target"                                           |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO4"      | "Availability" | 99          | " "           | 20            | 20                | 50            | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | "##ignore"                                                                | "Verify SLO creation with blank SLO Window Type"                                      |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO5"      | "Availability" | 99          | "Calendar"    | 20            | ' '               | 50            | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | "##ignore"                                                                | "Verify SLO creation with blank Critical Threshold"                                   |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO6"      | "Availability" | 99          | "Calendar"    | 20            | 20                | ' '           | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | "##ignore"                                                                | "Verify SLO creation with blank high Threshold"                                       |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO7"      | "Availability" | 99          | "Calendar"    | 20            | 20                | 50            | ' '             | "WEEK"         | 200            | "##ignore"      | 400                       | "##ignore"                                                                | "Verify SLO creation with blank Medium Threshold"                                     |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO8"      | "Availability" | 99          | "Rolling"     | ' '           | 20                | 50            | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | "##ignore"                                                                | "Verify SLO creation with blank Time Window"                                          |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SLO9"      | "Availability" | 99          | "Calendar"    | 'RemoveKey'   | 20                | 50            | 60              | 'RemoveKey'    | 200            | "##ignore"      | 400                       | 'Calendar Period can not be null for SLO with Calendar window'            | "Verify SLO creation without Calendar Period"                                         |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SL10"      | "Availability" | 99          | "Calendar"    | 60            | 20                | 50            | 60              | " "            | 200            | "##ignore"      | 400                       | "##ignore"                                                                | "Verify SLO creation with blank Calendar Period"                                      |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SL11"      | "Availability" | 99          | "Calendar"    | 80            | 20                | 50            | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | 'Time Window cannot be set for SLO with Calendar window'                  | "Verify SLO creation when Time window set for Calendar window"                        |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SL12"      | "Availability" | 99          | "Rolling"     | 80            | 20                | 50            | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | 'Calendar Period cannot be set for SLO with Rolling window'               | "Verify SLO creation when Calendar Period set for rolling window"                     |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SL12"      | "Availability" | 99          | "Rolling"     | 92            | 20                | 50            | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | 'Time Window must be a value between 1 to 90 for SLO with Rolling window' | "Verify SLO creation when Time Window set above 90"                                   |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SL12"      | "Availability" | 99.999999   | "Rolling"     | 92            | 20                | 50            | 60              | "WEEK"         | 200            | "##ignore"      | 400                       | 'SLO Target should be less than or equal to 99.999'                       | "Verify SLO creation when Target is above 99.999"                                     |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SL12"      | "Latency"      | 99.99       | "Rolling"     | 3             | 20                | 50            | 60              | "RemoveKey"    | 200            | "##ignore"      | 400                       | 'Duration is not defined for Latency SLO'                                 | "Verify SLO creation when Duration is not defined for Latency SLO"                    |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SL12"      | "Availability" | 99          | "Rolling"     | 1             | 90                | 50            | 10              | "RemoveKey"    | 200            | "##ignore"      | 400                       | 'Critical value cannot be greater than/equal to High/Medium value'        | "Verify SLO creation when Critical value set greater than/equal to High/Medium value" |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SL12"      | "Availability" | 99          | "Rolling"     | 10            | 20                | 50            | 10              | "RemoveKey"    | 200            | "##ignore"      | 400                       | 'Medium value cannot be less than/equal to Critical/High value'           | "Verify SLO creation when Medium value set less than/equal to Critical/High value"    |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SL12"      | "Availability" | 99          | "Rolling"     | 10            | 105               | 50            | 10              | "RemoveKey"    | 200            | "##ignore"      | 400                       | 'Critical value must be in the range 1-100'                               | "Verify SLO creation when Critical value not set in the range 1-100"                  |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SL12"      | "Availability" | 99          | "Rolling"     | 10            | 20                | 101           | 10              | "RemoveKey"    | 200            | "##ignore"      | 400                       | 'High value must be in the range 1-100'                                   | "Verify SLO creation when High value not set in the range 1-100"                      |
      | "OBS-223" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "slocustomer1" | "APAC" | "Azure"            | "observe-qa1-samplespringboot" | "SL12"      | "Availability" | 99          | "Rolling"     | 1             | 20                | 50            | 105             | "RemoveKey"    | 200            | "##ignore"      | 400                       | 'Medium value must be in the range 1-100'                                 | "Verify SLO creation when Medium value not set in the range 1-100"                    |

    * table updateslodata
      | testcase  | userName   | name          | verified | disabled | groupName       | email                  | SLOName    | SLOType        | target | windowType | timeWindow | Critical | High | Medium | calendarPeriod | Duration | Timeunit       | expectedStatus | expectedMessage | Scenario                                  |
      | "OBS-642" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "testSLO1" | "Availability" | 15     | "Calendar" | null       | 20       | 40   | 50     | "DAY"          | 100      | "milliseconds" | 200            | "##ignore"      | "Verify api of edit slo with valid input" |

    * table updatesloinvaliddata
      | testcase  | userName   | name          | verified | disabled | groupName       | email                  | CustomerId | SLOApplicationService | SLOName            | SLOType        | SLOTarget | SLOWindowType | SLOTimeWindow | CriticalThreshold | HighThreshold | MediumThreshold | calendarPeriod | Duration | Timeunit       | expectedStatus | expectedUpdateMessage                                                | Scenario                                                   |
      | "OBS-643" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "##ignore" | "##ignore"            | "RemoveKey"        | "Availability" | 15        | "Calendar"    | 1             | 20                | 40            | 50              | "DAY"          | 100      | "milliseconds" | 400            | "SLO name cannot be blank"                                           | "Verify api of edit slo without name "                     |
      | "OBS-643" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "##ignore" | "##ignore"            | ""                 | "Availability" | 15        | "Calendar"    | 2             | 20                | 40            | 50              | "DAY"          | 100      | "milliseconds" | 400            | "SLO name cannot be blank"                                           | "Verify api of edit slo with blank name"                   |
      | "OBS-643" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "##ignore" | "RemoveKey"           | "UpdateSLOInvalid" | "Availability" | 15        | "Calendar"    | 4             | 20                | 40            | 50              | "DAY"          | 100      | "milliseconds" | 400            | "SLO Application service cannot be blank"                            | "Verify api of edit slo without Application service"       |
      | "OBS-643" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "##ignore" | "##ignore"            | "UpdateSLOInvalid" | "Availability" | 15        | "RemoveKey"   | 6             | 20                | 40            | 50              | "DAY"          | 100      | "milliseconds" | 400            | "SLO Window Type should be specified"                                | "Verify api of edit slo without Window Type"               |
      | "OBS-643" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "##ignore" | "##ignore"            | "UpdateSLOInvalid" | "Availability" | 15        | "Calendar"    | 7             | "RemoveKey"       | 40            | 50              | "DAY"          | 100      | "milliseconds" | 400            | "Error budget critical status threshold for the SLO cannot be empty" | "Verify api of edit slo without critical status threshold" |
      | "OBS-643" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "##ignore" | "##ignore"            | "UpdateSLOInvalid" | "Availability" | 15        | "Calendar"    | 8             | 20                | "RemoveKey"   | 50              | "DAY"          | 100      | "milliseconds" | 400            | "Error budget high status threshold for the SLO cannot be empty"     | "Verify api of edit slo without high status threshold"     |
      | "OBS-643" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "##ignore" | "##ignore"            | "UpdateSLOInvalid" | "Availability" | 15        | "Calendar"    | 9             | 20                | 40            | "RemoveKey"     | "DAY"          | 100      | "milliseconds" | 400            | "Error budget medium status threshold for the SLO cannot be empty"   | "Verify api of edit slo without medium status threshold"   |

    * table customerdatawithoutmandotoryfield
      | testcase  | userName   | name           | verified | disabled | groupName | email                  | industryType | customerName | region | monitoringToolType | Critical    | High        | Medium      | APIKey     | AppId      | expectedStatus | expectedMessage                                                           | Scenario                                                  |
      | "OBS-174" | "obsadmin" | "APIadmintest" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "RemoveKey"  | "EMEA" | "Azure"            | 20          | 60          | 80          | "##ignore" | "##ignore" | 400            | "Customer name cannot be blank"                                           | "Admin create customer without Customer name"             |
      | "OBS-174" | "obsadmin" | "APIadmintest" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer87" | "EMEA" | "Azure"            | "RemoveKey" | 60          | 80          | "##ignore" | "##ignore" | 400            | "Error budget critical status threshold for the customer cannot be empty" | "Admin create customer without critical status threshold" |
      | "OBS-174" | "obsadmin" | "APIadmintest" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer87" | "EMEA" | "Azure"            | 20          | "RemoveKey" | 80          | "##ignore" | "##ignore" | 400            | "Error budget high status threshold for the customer cannot be empty"     | "Admin create customer without high status threshold"     |
      | "OBS-174" | "obsadmin" | "APIadmintest" | true     | false    | "ADMIN"   | "admintest@sample.com" | "Aerospace"  | "customer87" | "EMEA" | "Azure"            | 20          | 60          | "RemoveKey" | "##ignore" | "##ignore" | 400            | "Error budget medium status threshold for the customer cannot be empty"   | "Admin create customer without medium status threshold"   |

    * table customerdataforalert
      | testcase                  | userName   | name           | verified | disabled | groupName       | email                  | industryType | customerName    | region | monitoringToolType | alertType | AlertGroupName      | type          | updatedGroupName    | updatedType  | Critical | High | Medium | updatedIndustryType | updatedName   | updatedRegion | updatedCritical | updatedHigh | updatedMedium | expectedStatus | expectedUpdateStatus|expectedMessage |expectedUpdateMessage| Scenario                                       |
      | "OBS-940,OBS-943,OBS-945" | "obsadmin" | "APIadmintest" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Aerospace"  | "alertcustomer" | "EMEA" | "Azure"            | "Teams"   | "APIcustAlertGroup" | "Engineering" | "updatedGroupAlert" | "Operations" | 20       | 60   | 80     | "Computer"          | "updatedName" | "AMER"        | 30              | 50          | 70            | 200            |   200                  |"##ignore"     |"##ignore" | "Admin create customer with all Alert details" |

    * table createslodatawithalert
      | testcase                  | userName   | name          | verified | disabled | groupName       | email                  | industryType | customerName       | region | monitoringToolType | alertType | AlertGroupName     | type          | updatedGroupName    | updatedType  | SLOName       | SLOType        | target | windowType | timeWindow | Critical | High | Medium | calendarPeriod | Duration | Timeunit       | alertName | errorBudgetThreshold | updatedAlertName | updateErrorBudgetThreshold | expectedStatus | expectedMessage | Scenario                                 |
      | "OBS-941,OBS-944,OBS-946" | "obsadmin" | "APIobsadmin" | true     | false    | "OBSERVE_ADMIN" | "admintest@sample.com" | "Transport"  | "alertslocustomer" | "APAC" | "Azure"            | "Teams"   | "APIsloAlertGroup" | "Engineering" | "updatedGroupAlert" | "Operations" | "SingleALERT" | "Availability" | 99     | "Calendar" | null       | 20       | 40   | 50     | "DAY"          | 100      | "milliseconds" | "Alert50" | 50                   | "alert10"        | 10                         | 200            | "##ignore"      | "Verify SLO creation with alert details" |

